### ISSUE TITLE
Suggest & provide GHA workflow

### ISSUE THREAD

**Issue by maelle** [cynkra/fledge#268] opened 2022-04-08 14:15 UTC
E.g. daily bump_version()

**Comment by krlmlr** [comment] 2022-04-09 05:25
Also perhaps a daily synchronization from `NEWS.md` to tags.

**Comment by krlmlr** [comment] 2022-04-09 05:25
Also perhaps a daily synchronization from `NEWS.md` to tags.

**Comment by krlmlr** [comment] 2022-04-09 06:18
The sync workflow should also be triggered by changes to `NEWS.md` in the main branch.

**Comment by maelle** [comment] 2022-05-20 09:57
So part of this issue actually needs #31

**Comment by maelle** [comment] 2022-05-23 06:58
Person to tell about the workflow once it is functional https://twitter.com/MickaelCanouil/status/1528108623611699202

**Comment by maelle** [comment] 2022-07-26 10:03
#31 should be tackled first so putting it in this milestone

**Comment by maelle** [comment] 2022-07-26 11:47
Still useful to work on daily bump though

**Comment by krlmlr** [comment] 2022-09-07 05:02
`gh_whoami()` doesn't work from GHA: https://github.com/cynkra/fledge/runs/8220853540?check_suite_focus=true#step:5:115 .

**Comment by maelle** [comment] 2022-09-26 09:53
There's a bug somewhere given there are repeated items in https://github.com/cynkra/fledge/blob/main/NEWS.md
I'll look into it

**Comment by maelle** [comment] 2022-09-26 10:12
Right now locally, if I run `update_news()` I get the expected 

```markdown
- Same as previous version.
```

**Comment by krlmlr** [comment] 2022-09-27 03:26
Forgot to mention: as discussed yesterday, the problem is fixed by now with 06cba7f1b641d654ff1b76324f109f07ba4975a0. The reason was a ping-pong where a no-op bump led to an overwritten tag, which then led to treating this NEWS items as new.

**Comment by krlmlr** [comment] 2023-02-04 14:01
No need to act for now.

**Closed by krlmlr** 2023-02-04 14:01 UTC
Labels: for GitHub Actions :rocket:
