### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by krlmlr** [cynkra/fledge#5] opened 2018-04-26 21:10 UTC
~~and submit to CRAN.~~

**Comment by krlmlr** [comment] 2021-07-25 08:14
We can focus on snapshot tests for now. We can set a few environment variables to keep output stable (including Git SHAs), the vignette already has code that does it.

**Comment by krlmlr** [comment] 2021-08-02 09:51
I have `galley.R`, `aaa-galley.R` and `test-vignette-*.R` in tibble, these can be copied so that we get snapshot tests for vignettes. Let's add formal tests later.

**Comment by maelle** [comment] 2021-09-23 14:09
Actually is this a duplicate of #103

**Comment by krlmlr** [comment] 2021-09-30 19:31
This issue is about adding "any kind of test", #103 is about formal tests for internal functions. Testing the vignettes (including their output) is a start, maybe we don't need to strictly separate both kinds of test.

**Comment by maelle** [comment] 2021-10-01 08:12
What do you mean by formal tests?

**Comment by krlmlr** [comment] 2021-10-01 19:36
A regular explicit `test_that("some behavior", { ... })`, as opposed to a snapshot test.

**Closed** 2021-12-07 08:24 UTC
